VirtualAdvocate/Models/AccountService.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualAdvocate.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountService
    {
        public int ServiceId { get; set; }
        public string Service { get; set; }
        public string ServicesDescription { get; set; }
        public bool IsEnabled { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}

VirtualAdvocate/Controllers/UsersManagementController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using VirtualAdvocate.BLL;
using VirtualAdvocate.Common;
using VirtualAdvocate.DAL;
using VirtualAdvocate.Models;

namespace VirtualAdvocate.Controllers
{
    public class UsersManagementController : BaseController
    {
        private VirtualAdvocateEntities db = new VirtualAdvocateEntities();
        private VirtualAdvocateDocumentData objData = new VirtualAdvocateDocumentData();
        // GET: UsersManagement
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UserList(string enable)
        {
            Session["re"] = "Yes";
            bool active;
            if (string.IsNullOrEmpty(enable))
            {
                active = true;
                enable = "Active";
            }
            else
            {
                if (enable == "Active")
                    active = true;
                else
                    active = false;
            }

            ViewBag.Enable = enable;
            int myRoleID = Convert.ToInt32(Session["RoleId"]);
            // Only individual and due diligence user
            if (Convert.ToInt32(Session["RoleId"]) == 1)
            {
                if (active)
                {
                    var obj = (from ua in db.UserAddressDetails
                               join up in db.UserProfiles on ua.UserId equals up.UserID
                               join rol in db.Roles on up.RoleId equals rol.RoleId
                               where up.IsEnabled == active && up.UnusedUser != active

                               select new AllUserList { EmailAddress = up.EmailAddress, FirstName = ua.FirstName, LastName = ua.LastName, RoleDescription = rol.RoleDescription, UserID = up.UserID, IsEnabled = up.IsEnabled, CreatedDate = up.CreatedDate, IsLocked = up.UnusedUser }).ToList().OrderByDescending(y => y.CreatedDate).OrderBy(x => x.IsEnabled);
                    return View(obj.ToList());
                }
                else
                {
                    var obj = (from ua in db.UserAddressDetails
                               join up in db.UserProfiles on ua.UserId equals up.UserID
                               join rol in db.Roles on up.RoleId equals rol.RoleId
                               where up.IsEnabled == active || up.UnusedUser != active

                               select new AllUserList { EmailAddress = up.EmailAddress, FirstName = ua.FirstName, LastName = ua.LastName, RoleDescription = rol.RoleDescription, UserID = up.UserID, IsEnabled = up.IsEnabled, CreatedDate = up.CreatedDate, IsLocked = up.UnusedUser }).ToList().OrderByDescending(y => y.CreatedDate).OrderBy(x => x.IsEnabled);
                    return View(obj.ToList());
                }

            }
            else if (Convert.ToInt32(Session["RoleId"]) == 6) //company users
            {
               int Department = Convert.ToInt32(Session["DepartmentId"]);
                int orgID = Convert.ToInt32(Session["OrgId"]);
                var obj = (from ua in db.UserAddressDetails
                           join up in db.UserProfiles on ua.UserId equals up.UserID
                           join rol in db.Roles on up.RoleId equals rol.RoleId
                           where rol.RoleId != 1 && up.OrganizationId == orgID && (Department == 0 || (Department != 0 && up.Department == Department)) && up.IsEnabled == active &&
                          ((myRoleID == 6 && up.RoleId == 5)
                          ||
                           (myRoleID == 2 && up.RoleId != 2) || myRoleID == 1)
                           select new AllUserList { EmailAddress = up.EmailAddress, FirstName = ua.FirstName, LastName = ua.LastName, RoleDescription = rol.RoleDescription, UserID = up.UserID, IsEnabled = up.IsEnabled, IsLocked = up.UnusedUser }).ToList();
                return View(obj.ToList());
            }
            else
            {
                int userId;
                userId = Convert.ToInt32(Session["UserId"]);
                var obj = (from ua in db.UserAddressDetails
                           join up in db.UserProfiles on ua.UserId equals up.UserID
                           join rol in db.Roles on up.RoleId equals rol.RoleId
                           join org in db.OrganizationDetails on up.OrganizationId equals org.OrganizationId
                           where up.UserID == userId && up.IsEnabled == active && up.UnusedUser != active
                           select new AllUserList { EmailAddress = up.EmailAddress, FirstName = ua.FirstName, LastName = ua.LastName, RoleDescription = rol.RoleDescription, UserID = up.UserID, IsEnabled = up.IsEnabled, CreatedDate = up.CreatedDate, IsLocked = up.UnusedUser }).ToList().OrderByDescending(y => y.CreatedDate).OrderBy(x => x.IsEnabled);
                return View(obj.ToList());
            }

            
        }

        [AllowAnonymous]
        [HttpPost]
        public JsonResult ActivateProfile(int? id)
        {
            HttpContext.Response.StatusCode = (int)HttpStatusCode.OK;
            var message = string.Empty;
            var test = 0;
            bool LogSts = false;
            try
            {
                VirtualAdvocateData objData = new VirtualAdvocateData();
                LogRegistration objLog = new LogRegistration();
                var obj = db.UserProfiles.Where(ua => ua.UserID == id).FirstOrDefault();
                if (obj != null)
                {
                  
                    if (obj.IsEnabled == true && obj.HasActivated == true && obj.UnusedUser == false)
                    {
                        obj.IsEnabled = false;
                        obj.HasActivated = false;
                      
                        message = "User profile deactivated successfully";
                        objLog.Action = "Inactive";
                        objLog.IsEnabled = false;
                        LogSts = false;
                    }
                    else
                    {
                        LoginHistory objLoginLog = new LoginHistory();

                        objLoginLog.LoginDate = DateTime.Now;
                        objLoginLog.Status = 1;
                        objLoginLog.UserId = obj.UserID;

                        db.LoginHistories.Add(objLoginLog);
                       
                        LogSts = true;
                        objLog.Action = "Active";
                        objLog.IsEnabled = true;
                        obj.IsEnabled = true;
                        obj.UnusedUser = false;
                        obj.HasActivated = true;
                        message = "User profile activated successfully";
                        var objAddress = db.UserAddressDetails.Where(x => x.UserId == id).FirstOrDefault();
                        MailSend objMail = new MailSend();
                        objMail.ActivationNotificationEmail(objAddress.FirstName + " " + objAddress.LastName, obj.EmailAddress, ConfigurationManager.AppSettings["ApplicationTitle"].ToString(), Common.Helper.GetBaseUrl());
                    }
                    var objUserRegistration = db.UserAddressDetails.Where(ua => ua.UserId == id).FirstOrDefault();

                    // Assign Values for Log
                    objLog.UserId = id.Value;
                    objLog.FirstName = objUserRegistration.FirstName;
                    objLog.LastName = objUserRegistration.LastName;
                    objLog.EmailAddress = obj.EmailAddress;
                    objLog.PhoneNumber = objUserRegistration.PhoneNumber;
                    objLog.StreetName = objUserRegistration.StreetName;
                    objLog.PlotNumber = objUserRegistration.PlotNumber;
                    objLog.Region = objUserRegistration.Region;
                    objLog.BuildingName = objUserRegistration.BuildingName;
                    objLog.LandMark = objUserRegistration.LandMark;
                    objLog.BlockNumber = objUserRegistration.BlockNumber;
                    objLog.ModifierId = Convert.ToInt32(Session["UserId"]);
                    objLog.RoleId = obj.RoleId;
                    objLog.OrgId = obj.OrganizationId;
                    objLog.ModifiedDate = DateTime.Now;
                    if (obj.RoleId == 4)
                    {

                        objData.LogDueRegistrations(id.Value, LogSts, Convert.ToInt32(Session["UserId"]));
                    }
                    else
                    {
                        objData.LogRegistrations(objLog);
                    }


                }
                db.SaveChanges();
                test = 1;
            }
            catch (Exception ex)
            {
                ErrorLog.LogThisError(ex);
                message = "An error occured while processing the request. Try again later";
                HttpContext.Response.StatusCode = (int)HttpStatusCode.BadRequest;

            }
            if (test == 1)
                return Json(new { message = message }, JsonRequestBehavior.AllowGet);
            else
                return Json(new { ErrorMessage = "not saved" }, JsonRequestBehavior.AllowGet);
        }

        //public ActionResult ActivateProfile(int? id)
        //{
        //    var message = string.Empty;
        //    try
        //    {
        //        var obj = db.UserProfiles.Where(ua => ua.UserID == id).FirstOrDefault();
        //        if (obj != null)
        //        {
        //            if (obj.IsEnabled == true && obj.HasActivated == true)
        //            {
        //                obj.IsEnabled = false;
        //                obj.HasActivated = false;

VirtualAdvocate/Views/UsersManagement/AddOrgUser.cshtml
@model VirtualAdvocate.Models.OrgUserViewModel
@{
    if (Convert.ToInt32(Session["RoleId"]) == 1)
    {
        ViewBag.MenuActive = "Organization";
    }
    else {
        ViewBag.MenuActive = "UserManagement";
    }
   
            //ViewBag.Title = "AddOrgUser";
            Layout = "~/Views/Shared/_Layoutmain.cshtml";
        }

<h2>ADD ORGANIZATION USER</h2>
<hr />
@using(Html.BeginForm("AddOrgUser", "UsersManagement", FormMethod.Post, new { @class = "form-horizontal", role = "form",id= "formData", onsubmit = "showProgress()" }))
{
    @Html.AntiForgeryToken()

    @*@Html.ValidationSummary("", new { @class = "text-danger" })*@

    <div class="row">
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>User Details</legend>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.HiddenFor(m=>m.OrgId)
                                @Html.LabelFor(m => m.FirstName, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "First Name" })
                                    @Html.ValidationMessageFor(m => m.FirstName, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.EmailAddress, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", @placeholder = "Email Address" })
                                    @Html.ValidationMessageFor(m => m.EmailAddress, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.password, new { @class = "col-lg-6 control-label" })

                                <div class="col-lg-6">
                                    @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password" })
                                    @Html.ValidationMessageFor(m => m.password, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Confirmpassword, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.PasswordFor(m => m.Confirmpassword, new { @class = "form-control", @placeholder = "Confirm Password" })
                                    @Html.ValidationMessageFor(m => m.Confirmpassword, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                @Html.LabelFor(m => m.LastName, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                    @Html.ValidationMessageFor(m => m.LastName, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Designation, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.Designation, new { @class = "form-control", @placeholder = "Designation" })
                                    @Html.ValidationMessageFor(m => m.Designation, string.Empty, new { @class = "" })
                                </div>
                            </div>
                            @if (Convert.ToInt32(Session["RoleId"]) != 6)
                            {
                            <div class="form-group">
                                @Html.LabelFor(m => m.Department, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.DropDownListFor(m => m.Department, new SelectList(Model.getDepartmentList, "ID", "Name"), "-Select-", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.Department, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            }

                            <div class="form-group">
                                @Html.LabelFor(m => m.RoleID, new { @class = "col-lg-6 control-label" })
                                <div class="col-lg-6">
                                    @Html.DropDownListFor(m => m.RoleID, new SelectList(Model.getRoleList, "ID", "Name"), "-Select-", new { @class = "form-control" })
                                    @Html.ValidationMessageFor(m => m.RoleID, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>


                    </div>

                </fieldset>
            </div>
        </div>
    </div>
        @*<div class="col-lg-12">
            <div class="well bs-component">
                <fieldset class="checkBoxListFor">
                    <legend>Clients Required</legend>
                    <div class="form-group">
                        <div class="col-lg-12 form-inline">
                            @Html.CheckBoxListFor(model => model.PostedServices.ServiceIds, model => model.AvailableService, m => m.Id, m => m.Name, model => model.SelectedService)
                            @Html.ValidationMessageFor(model => model.PostedServices.ServiceIds, string.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>*@

        @*<div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>Preferred Payment Method</legend>
                    <div class="form-group">
                        <div class="col-lg-6 form-inline">
                            @Html.CheckBoxListFor(model => model.PostedPaymentMethods.PaymentTypeIds, model => model.AvailablePaymentMethods, m => m.Id, m => m.Name, model => model.SelectedPaymentMethods)
                            @Html.ValidationMessageFor(model => model.PostedPaymentMethods.PaymentTypeIds, string.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>*@

        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-2">
                    <input type="submit" class="btn btn-default" value="Submit" />
                </div>
                @{ var Controllername = "Login"; var action = "Index";}
                @if (Convert.ToInt32(Session["RoleId"]) == 1 || Convert.ToInt32(Session["RoleId"]) == 2) { Controllername = "UsersManagement"; action = "OrgUserList"; }
                <div class="">
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel" onclick="location.href='@Url.Action(action,Controllername, new { id=Model.OrgId})'">Cancel</button>
                </div>
            </div>
        </div>
   
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script type="text/javascript">
//    $(function () {

//        $('input[name="PostedPaymentMethods.PaymentTypeIds"]').rules('add', {
//    required: true,
//    messages: {
//        required: "Select Atleast One Payment Method"
//    }
//});

//});
    $(function () {

        $('input[name="PostedServices.ServiceIds"]').rules('add', {
            required: true,
            messages: {
                required: "Select Atleast One Service"
            }
        });

    });
   
    </script>
}

VirtualAdvocate/Views/UsersManagement/Development.cshtml
@{
    //ViewBag.Title = "Development";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>UNDER DEVELOPMENT</h2>

<div class="container">
    <div class="row">
        <div class="col-lg-6">
            <div class="alert alert-dismissible alert-success">                
                <h4>Requested page under development process</h4>
                <p>coming soon..</p>
            </div>
        </div>
    </div>
</div>

VirtualAdvocate/Views/UsersManagement/EditAcService.cshtml
@model VirtualAdvocate.Models.AccountServiceModel
@{
    //ViewBag.Title = "EditAcService";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>EDIT CLIENT</h2>
<hr />
@using (Html.BeginForm("EditAcService", "UsersManagement", FormMethod.Post, new { @class = "form-horizontal", role = "form"  onsubmit = "showProgress()" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset class="checkBoxListFor">
                    <legend>Client Required</legend>
                    <div class="form-group">
                        @Html.HiddenFor(m=>m.userId)
                        <div class="col-lg-12 form-inline">

                            @foreach (var s in Model.AvailableService)
                            {
                                @*@Html.RadioButton("AvailableService", s.Id,s.IsSelected)*@
                                <label>
                                   @if (s.IsSelected)
                                    {
                                    @Html.RadioButtonFor(Model => Model.AvailableService, s.Id, new { @checked = "checked" })
                                    }
                                    else
                                    {
                                    @Html.RadioButtonFor(Model => Model.AvailableService, s.Id)
                                    }
                                    @Html.Label(s.Name)
                                    </label>

                                    }


</div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-2">
                    <input type="submit" class="btn btn-default" value="Save Changes" />
                </div>
                <div class="">
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel"  onclick="history.go(-1);">Cancel</button>
                </div>
            </div>
        </div>
    </div>
                    }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script type="text/javascript">   
    $(function () {       
        $('input[name="PostedServices.ServiceIds"]').rules('add', {
            required: true,
            messages: {
                required: "Select Atleast One Client"
            }
        });

    });

        @*function saveChanges()
    {
            $.ajax({
                url: '@Url.Content("~/UsersManagement/EditAcService")',
                type: 'POST',
                data: { id: id,SelectedServicee:"" },
                dataType: 'json',
                success: function (result) { location.reload(); },
                error: function () { alert('Error!'); }
            });
    }*@
    </script>
}

VirtualAdvocate/Views/UsersManagement/EditPayment.cshtml
@model VirtualAdvocate.Models.EditPaymentMethodeModel
@{
    //ViewBag.Title = "EditPayment";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>EDIT PAYMENT</h2>
<hr />
@using (Html.BeginForm("EditPayment", "UsersManagement", FormMethod.Post, new { @class = "form-horizontal", role = "form"  onsubmit = "showProgress()" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset class="checkBoxListFor">
                    <legend>Services Required</legend>
                    <div class="form-group">
                        @Html.HiddenFor(m => m.userId)
                        <div class="col-lg-12 form-inline">
                            @Html.CheckBoxListFor(model => model.PostedPaymentMethods.PaymentTypeIds, model => model.AvailablePaymentMethods, m => m.Id, m => m.Name, model => model.SelectedPaymentMethods)
                            @Html.ValidationMessageFor(model => model.PostedPaymentMethods.PaymentTypeIds, string.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-2">
                    <input type="submit" class="btn btn-default" value="Save Changes" />
                </div>
                <div class="">
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel" onclick="history.go(-1);">Cancel</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script type="text/javascript">
        $(function () {

            $('input[name="PostedPaymentMethods.PaymentTypeIds"]').rules('add', {
                required: true,
                messages: {
                    required: "Select atleast one payment method"
                }
            });

        });
    </script>
}

VirtualAdvocate/Views/UsersManagement/EditRole.cshtml
@model VirtualAdvocate.Models.EditUserRoleModel
@{
    //ViewBag.Title = "EditPayment";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>EDIT ROLE</h2>
<hr />
@using (Html.BeginForm("EditUserRole", "UsersManagement", FormMethod.Post, new { @class = "form-horizontal", role = "form" ,onsubmit = "showProgress()" } ))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset class="checkBoxListFor">
                    <legend>User Role</legend>
                    <div class="form-group">
                        @Html.HiddenFor(m => m.userId)
                        <div class="col-lg-12 form-inline">
                            @Html.DropDownListFor(m => m.UserRole, new SelectList(Model.Roles, "ID", "Name"), "-Select-", new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.UserRole, string.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-2">
                    <input type="submit" class="btn btn-default" value="Save Changes" />
                </div>
                <div class="">
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel" onclick="history.go(-1);">Cancel</button>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script type="text/javascript">
        $(function () {

            $('input[name="PostedPaymentMethods.PaymentTypeIds"]').rules('add', {
                required: true,
                messages: {
                    required: "Select atleast one payment method"
                }
            });

        });
    </script>
}

VirtualAdvocate/Views/UsersManagement/Index.cshtml
@model IEnumerable<VirtualAdvocate.Models.AllUserList>
@{
    ViewBag.MenuActive = "DashBoard";
    //ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}
<h2>Dash Board</h2>

VirtualAdvocate/Views/UsersManagement/_AccountServices.cshtml
@model VirtualAdvocate.Models.AccountServiceModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_AccountServices</title>
</head>
<body>
    <div> 
        <div class="well bs-component">
            <fieldset class="checkBoxListFor">
                <legend>Services Required</legend>
                <div class="form-group">
                    <div class="col-lg-12 form-inline">
                        @Html.CheckBoxListFor(model => model.PostedServices.ServiceIds, model => model.AvailableService, m => m.Id, m => m.Name, model => model.SelectedService)
                        @Html.ValidationMessageFor(model => model.PostedServices.ServiceIds, string.Empty, new { @class = "text-danger" })
                    </div>
                </div>
            </fieldset>
        </div>
        </div>
</body>
</html>