VirtualAdvocate/Controllers/MultipleDocumentDownloadController.cs
//using Microsoft.Office.Interop.Word;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using VirtualAdvocate.Common;
using VirtualAdvocate.DAL;
using VirtualAdvocate.Models;
using Ionic.Zip;
using System.Text.RegularExpressions;
using DocumentFormat.OpenXml.Packaging;
using OpenXmlPowerTools;
using System.Xml.Linq;
using Microsoft.Office.Interop.Word;

namespace VirtualAdvocate.Controllers
{
    public class MultipleDocumentDownloadController : BaseController
    {
        private VirtualAdvocateEntities db = new VirtualAdvocateEntities();
        private VirtualAdvocateDocumentData objData = new VirtualAdvocateDocumentData();

        public  int userID = Convert.ToInt32(System.Web.HttpContext.Current.Session["UserId"]);
        public  int orgId = Convert.ToInt32(System.Web.HttpContext.Current.Session["OrgId"]);
        public  int deptID = Convert.ToInt32(System.Web.HttpContext.Current.Session["DepartmentId"]);
        public  int roleId = Convert.ToInt32(System.Web.HttpContext.Current.Session["RoleId"]);

        // GET: MultipleDocumentDownload
        public ActionResult MultipleDownload(int? id)
        {
            Session.Remove("Displayorder");
         
            Session["AssociateCount"] = 0;
            DocumentTemplateListModel objTempList = new DocumentTemplateListModel();
            GetCustomerNameList();
            try
            {
                int roleID = Convert.ToInt32(Session["RoleId"]);
                int department = Convert.ToInt32(Session["DepartmentId"]);

                var objTemplates = (from ut in db.DocumentTemplates
                                    join dc in db.DocumentCategories on ut.DocumentCategory equals dc.DocumentCategoryId
                                    where ut.IsEnabled == true && dc.ServiceId==orgId
                                    && (((roleID != 6) && (roleID != 5)) || ((roleID == 6 && ut.DepartmentID == department) || (roleID == 5 && ut.DepartmentID == department) || roleID == 3))

                                    select new DocumentTemplateListModel { TemplateName = ut.DocumentTitle, TemplateId = ut.TemplateId, DocumentFileName = ut.TemplateFileName, DocumentCategory = dc.DocumentCategoryName, Cost = ut.TemplateCost, AssociatedDocumentId = ut.AssociateTemplateId, AssociatedDocument = null, ServiceId = dc.ServiceId, DocumentSubCategoryId = ut.DocumentSubCategory, DocumentSubSubCategoryId = ut.DocumentSubSubCategory, DocumentSubCategoryName = null, DocumentSubSubCategoryName = null }
                        );
            
                var query = objTemplates.Select(p => new DocumentTemplateListModel
                {
                    TemplateName = p.TemplateName,
                    TemplateId = p.TemplateId,
                    DocumentFileName = p.DocumentFileName,
                    DocumentCategory = p.DocumentCategory,
                    Cost = p.Cost,
                    AssociatedDocumentId = p.AssociatedDocumentId,
                    AssociatedDocument = "", //(from utt in db.DocumentTemplates where utt.TemplateId == p.AssociatedDocumentId select utt.DocumentTitle).FirstOrDefault(),
                    ServiceId = p.ServiceId,
                    DocumentSubCategoryId = p.DocumentSubCategoryId,
                    DocumentSubSubCategoryId = p.DocumentSubSubCategoryId,
                    DocumentSubCategoryName = (from dsc in db.DocumentSubCategories where dsc.DocumentSubCategoryId == p.DocumentSubCategoryId select dsc.DocumentSubCategoryName).FirstOrDefault(),
                    DocumentSubSubCategoryName = (from dssc in db.DocumentSubSubCategories where dssc.DocumentSubSubCategoryId == p.DocumentSubSubCategoryId select dssc.SubDocumentCategoryName).FirstOrDefault()

                });             
              
                return View(query);
            }
            catch (Exception ex)
            {
                ErrorLog.LogThisError(ex);
            }
            return View();
        }


        public ActionResult CreateDynamicForm(int? id)
        {
            try
            {
                string multiCustomers = string.Empty;
                var multipleCustomerids = new int[] { };
                int customer = 0;
                int CommonTempId;
                if (Session["TemplateId"] == null)
                {
                    Session["TemplateId"] = id;
                }
                CommonTempId = Convert.ToInt32(Session["TemplateId"]); // To maintain Parent Id for Associate Templates

                Session["CurrentTemplateId"] = id; // For FormConfirmation function

                string customerId = null;

                if (Request["CustomerId"] != null)
                {

                    customerId = Request["CustomerId"].ToString();
                    //Session["customerId"] = customerId;
                    string[] cusomers = customerId.ToString().TrimEnd(',').Split(',');

                    if (cusomers.Length > 0)
                    {

                        if (cusomers.Length > 1)
                        {
                            Session["MultipleCustomer"] = "Yes";

                            multipleCustomerids = new Int32[cusomers.Length];
                            string CustomerNames = string.Empty;
                            string CustomerIID = string.Empty;
                            for (int i = 0; i < cusomers.Length - 1; i++)
                            {
                                string[] customerDetails1 = cusomers[i].Split('|');

                                string[] emailAddress1 = customerDetails1[1].Split(':');

                                string email1 = emailAddress1[1].ToString().Replace(" ", "");
                                var customerID1 = db.CustomerDetails.Where(c => c.EmailAddress == email1).Select(c => c.CustomerId).FirstOrDefault();

                                CustomerNames = CustomerNames + db.CustomerDetails.Where(c => c.EmailAddress == email1).Select(c => c.CustomerName).FirstOrDefault() + ", ";

                                ViewBag.MultiName = CustomerNames.Trim(',');
                                Session["MultiName"] = ViewBag.MultiName;
                                multipleCustomerids.SetValue(customerID1, i);
                                multiCustomers = multiCustomers + customerID1.ToString() + ",";
                            }

                            Session["MultipleCustomerIDS"] = multiCustomers;

                        }
                        string[] customerDetails = cusomers[0].Split('|');

                        string[] emailAddress = customerDetails[1].Split(':');

                        string email = emailAddress[1].ToString().Replace(" ", "");
                        var customerID = db.CustomerDetails.Where(c => c.EmailAddress == email).Select(c => c.CustomerId).FirstOrDefault();

                        customer = customerID;
                        //  var customerDetails=
                        Session["customerId"] = customerID;


                    }



                }
                else
                {
                    ViewBag.MultiName = Session["MultiName"];
                    multiCustomers = (Session["MultipleCustomerIDS"]).ToString();
                }


                string AssociateName = "";
                int? associateId = null;
                int userId = Convert.ToInt32(Session["UserId"]);

                var objCurrentTemplate = db.DocumentTemplates.Find(id); // To get Parent Template Name

                AssociateName = objCurrentTemplate.DocumentTitle;
                //ViewBag.Head = "Form  " + objCurrentTemplate.DocumentTitle;



                // Checking associate template
                var objAssociateIds = db.AssociateTemplateDetails.Where(c => c.TemplateId == CommonTempId && c.IsEnabled == true).OrderBy(c => c.DisplayOrder);

                if (objAssociateIds != null && objAssociateIds.Count() >= 1)
                {
                    if (Session["ATCount"] == null)
                        Session["ATCount"] = objAssociateIds.Count();    // Total Associate Count

                    //if (Session["AssociateCount"] != null && Convert.ToInt32(Session["AssociateCount"]) > 1)
                    //{
                    //    DisplayOrder = Convert.ToInt32(Session["AssociateCount"]);
                    //}

                    //var objAssociateid = objAssociateIds.Where(d => d.DisplayOrder == DisplayOrder).ToList();
                    if (objAssociateIds != null)
                    {
                        AssociateName = "Associated Documents >> ";
                        foreach (AssociateTemplateDetail item in objAssociateIds)
                        {
                            var objAssociate = db.DocumentTemplates.Find(item.AssociateTemplateId);
                            if (objAssociate != null)
                            {
                                string currentdoc = string.Empty;

                                if (item.Mandatory)
                                {
                                    if (objAssociate.DocumentTitle == objCurrentTemplate.DocumentTitle)
                                    {
                                        currentdoc = "<font color =red><b>" + objAssociate.DocumentTitle + "</b></font>";

                                    }
                                    else
                                    {
                                        currentdoc = "<font color =red>" + objAssociate.DocumentTitle + "</font>";
                                    }
                                }
                                else if (objAssociate.DocumentTitle == objCurrentTemplate.DocumentTitle)
                                {
                                    currentdoc = "<b>" + objAssociate.DocumentTitle + "</b>";

VirtualAdvocate/Views/MultipleDocumentDownload/BulkDocuments.cshtml
@model IEnumerable<VirtualAdvocate.Models.BulkDocumentTemplateListModel>

@{
    ViewBag.MenuActive = "BulkDocuments";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>Bulk Documents</h2>
<!-- DataTables CSS -->
<link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
<!-- DataTables Responsive CSS -->
<link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

<form name="form" method="post">
   
    <div class="row">
        <div class="col-md-9">
            <div class="navbar-form navbar-right" role="search">
            </div>
        </div>
    </div>


    <table class="table table-striped table-hover dataTable table-custom-border" id="tblTemplateList">
        <thead>
            <tr>
                <th>#</th>
                <th>@Html.DisplayName("Template")</th>
                <th>@Html.DisplayName("Category")</th>
                @*<th>@Html.DisplayName("SubCategory")</th>
                <th>@Html.DisplayName("Sub SubCategory")</th>*@
                <th>@Html.DisplayName("Cost")</th>
                <th>@Html.DisplayName("Created On")</th>
                <th>View</th>
                <th>Download</th>
            </tr>
        </thead>
        <tbody>
            @{int rowNo = 0;}
            @foreach (var item in Model)
            {
                rowNo = rowNo + 1;
                <tr>
                    <td>@rowNo</td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TemplateName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DocumentCategory)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.DocumentSubCategoryName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DocumentSubSubCategoryName)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CreatedOn)
                    </td>
                    <td>
                        @*<a href="@Url.Action("CreateDynamicForm","DocumentManagement",new { id = item.TemplateId })" title="Fill">Fill</a>*@
                        <a  href="@Url.Action("GetDocuments","MultipleDocumentDownload",new { id = item.BulkTemplateID })"  class="fa fa-eye" title="View"></a>

                    </td>
                    <td>
                        <a href="@Url.Action("BulkDocumentDownload","MultipleDocumentDownload",new { id = item.BulkTemplateID })" class="fa fa-download" title="Download"></a>

                    </td>

                </tr>

            }

        </tbody>
    </table>
</form>

@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>
    <script type="text/javascript">
            $(document).ready(function () {
                $('#tblTemplateList').DataTable({
                    "ordering": false,
                    responsive: true
                });

            });
</script>
}

VirtualAdvocate/Views/MultipleDocumentDownload/BulkDownload.cshtml
@model IEnumerable<VirtualAdvocate.Models.FilledFormDetailModel>
@{
    ViewBag.MenuActive = "FormsHistory";
    //ViewBag.Title = "Forms History";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>Bulk Download</h2>

<!-- DataTables CSS -->
<link href="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.css")" rel="stylesheet" type="text/css" />
<!-- DataTables Responsive CSS -->
<link href="@Url.Content("~/bower_components/datatables-responsive/css/dataTables.responsive.css")" rel="stylesheet" type="text/css" />

@using (Html.BeginForm("DownloadMultipleDocuments", "MultipleDocumentDownload", FormMethod.Get, new AjaxOptions { UpdateTargetId = "result", LoadingElementId = "loading", onsubmit = "showProgress()" }))
{
    <div id="loading" style="display:none;">Generating Report...</div>
<div class="row" id="result">
    <div class="col-md-12">
        <table class="table table-striped table-hover dataTable table-custom-border" id="tblTemplateKeyList">
            <thead>
                <tr>
                    <th><input name="select_all" value="1" type="checkbox"></th>
                   
                    <th>
                        Customer
                    </th>
                    <th>
                        Document Title
                    </th>
                    <th>
                        Cost
                    </th>
                    <th>
                        Date Created
                    </th>
                </tr>
            </thead>
            <tbody>
              @{int rowNo = 0;
                  int tempGroupId = 0;
                  var outlinecss = ""; }
                @foreach (var item in Model)
                {

                    rowNo = rowNo + 1;
                    if (rowNo == 1)
                    {
                        tempGroupId = item.GroupId;

                    }
                    if (rowNo > 1)
                    {
                        if (item.GroupId != tempGroupId)
                        {

                            outlinecss = "outline-table";

                        }
                        else { outlinecss = ""; }

                    }

                    <tr  class="@outlinecss">
                        <td>
                            <input type="checkbox" class="check" name="FilledTemplateName" id="FilledTemplateName" value=@item.FilledTemplateName.Replace(" ","_").Replace("docx","pdf") />
                        </td>
                       
                        <td>
                            @Html.DisplayFor(modelItem => item.CustomerName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.DocumentTitle)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Amount)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CreatedDate)
                        </td>
                      
                    </tr>
                    tempGroupId = item.GroupId;
                   
                }
            </tbody>
        </table>
    </div>
</div>

<input type="submit" value="Download selected documents" class="btn btn-default" id="submit" disabled='disabled'/>

                  }
@section Scripts {

    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/unobtrusive")
    <script src="@Url.Content("~/bower_components/datatables/media/js/jquery.dataTables.min.js")"></script>
    <script src="@Url.Content("~/bower_components/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js")"></script>
    <script type="text/javascript">
            $(document).ready(function () {
                $('#tblTemplateKeyList').DataTable({
                    "ordering": false,
                    responsive: true
                });

            });

           
            // Handle click on "Select all" control
            $("input[name='select_all']").on('click', function (e) {
                var submit = document.getElementById('submit');
                var table = $('#tblTemplateKeyList').DataTable();

                if (this.checked) {
                 
                    $(':checkbox', table.rows({ page: 'current' }).nodes()).prop('checked', this.checked);
                    submit.disabled = false;
                  //  $('#tblTemplateKeyList tbody input[type="checkbox"]:not(:checked)').trigger('click');
                } else {
                    submit.disabled = true;
                    $(':checkbox', table.rows({ page: 'current' }).nodes()).prop('checked', false);
                   // $('#tblTemplateKeyList tbody input[type="checkbox"]:checked').trigger('click');
                }

                // Prevent click event from propagating to parent
                e.stopPropagation();
            });

            $('.check').change(function () {
                if ($('.check:checked').length) {
                    $('#submit').removeAttr('disabled');
                } else {
                    $('#submit').attr('disabled', 'disabled');
                }
            });

    </script>
}

VirtualAdvocate/Views/MultipleDocumentDownload/CoverLetterConfirm.cshtml
@{
    ViewBag.Title = "CoverLetterConfirm";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2> Cover Letter Confirmation</h2>

<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            <b>Selected Customer Names:</b> @ViewBag.MultiName<br />

        </div>

    </div>
</div>

<hr />
@using (Html.BeginForm("CoverLetterConfirmed", "DocumentManagement", FormMethod.Post, new { @class = "form-horizontal", role = "form", onsubmit = "showProgress()" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>Cover Letter Confirmation</legend>
                    <div class="form-group">
                        <div class="col-lg-12">
                            <div>
                                <label>
                                    There is a Associate document. Would you like to fill those document? or Create cover letter for filled document?
                                </label>
                            </div>

                        </div>
                    </div>
                </fieldset>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-4">
                    @*<input type="submit" class="btn btn-default" value="Continue Associate Document" />*@
                    @{ var Controllername1 = "MultipleDocumentDownload"; var action1 = "CreateDynamicForm"; var id = @ViewBag.AssociateId;}
                    <button type="button" class="btn btn-default" value="Continue Associate Document" onclick="location.href='@Url.Action(action1,Controllername1, new { @id = id })'">Continue Associate Document</button>
                </div>
                <div class="col-md-4">
                    <button type="button" class="btn btn-default" value="Skip" onclick="location.href='@Url.Action("Skip","MultipleDocumentDownload", new { @id = id })'">Skip</button>

                </div>
                @if (ViewBag.lastdoc == "true")
                {
                    var Controllername = "MultipleDocumentDownload"; var action = "CoverLetterConfirmed";
                    <div class="">
                        <button type="button" value="Create CoverLetter" class="btn btn-cancel" id="btncancel" onclick="location.href='@Url.Action(action, Controllername)'">Create CoverLetter</button>
                    </div>
                }
            </div>
        </div>
    </div>
                        }

VirtualAdvocate/Views/MultipleDocumentDownload/CreateDynamicForm.cshtml
@{
    ViewBag.MenuActive = "MultipleDownload";

    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            <b>Selcted Customer Names:</b> @ViewBag.MultiName<br />
          
        </div>

    </div>
</div>

@Html.Raw(@ViewBag.Dynamic)
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")

    <script type="text/javascript">
        $('#btnSubmit').button();
        $('#btnSubmit').click(function () {
    $(this).html('<img src="http://www.bba-reman.com/images/fbloader.gif" />');
});

       

    </script>

}

VirtualAdvocate/Views/MultipleDocumentDownload/HTMLEditor.cshtml
@{
    ViewBag.Title = "HTMLEditor";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}
    <meta name="viewport" content="width=device-width" />
    <title>TinyMCE Example</title>
    <!-- TinyMCE Script Reference -->
<script src="~/Scripts/tinymce/tinymce.min.js"></script>
  

<h2>EDIT DOCUMENT</h2>

<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            <b>Selected Customer Names:</b> @ViewBag.MultiName<br/>

        </div>

    </div>
</div>

@using (Html.BeginForm("SaveDocument", "MultipleDocumentDownload", FormMethod.Post))
{
<div class="row">
    <div class="col-lg-12">
        <div class="well bs-component">
            <input type=hidden name="customerId">
            <textarea id="txtEditor">@Html.Raw(@ViewBag.WordContent)</textarea>         
        </div>
    </div>
</div>

}
    <!-- Script to wire up your TinyMCE editor -->
@section Scripts{
    <script type="text/javascript">
    $(document).ready(function () {

            tinymce.EditorManager.editors = [];
            tinymce.init({
                selector: "#txtEditor",
                theme: "modern",
                paste_data_images: true,
                height: "500",
                menubar:"hide",
                plugins: [
                  //"advlist autolink lists link image charmap print preview hr anchor pagebreak",
                  "searchreplace wordcount visualblocks visualchars code fullscreen",
                  "insertdatetime media nonbreaking save table contextmenu directionality",
                  "emoticons template paste textcolor colorpicker textpattern"
                ],
                toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | forecolor backcolor",
              
                file_picker_callback: function (callback, value, meta) {
                    if (meta.filetype == 'image') {
                        $('#upload').trigger('click');
                        $('#upload').on('change', function () {
                            var file = this.files[0];
                            var reader = new FileReader();
                            reader.onload = function (e) {
                                callback(e.target.result, {
                                    alt: ''
                                });
                            };
                            reader.readAsDataURL(file);
                        });
                    }
                },
                templates: [{
                    title: 'Test template 1',
                    content: 'Test 1'
                }, {
                    title: 'Test template 2',
                    content: 'Test 2'
                }]
            }).then(function (editors) {
                if (editorDescription != undefined && editorDescription != "") {
                    tinyMCE.activeEditor.setContent(editorDescription);
                }
            });

    })

    </script>
}

VirtualAdvocate/Views/MultipleDocumentDownload/PreviewDocument.cshtml
@{
    ViewBag.MenuActive = "MultipleDownload";

    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}


<h2>PREVIEW DOCUMENT</h2>
<div class="row">
    <div class="col-lg-6">
        <div class="form-group">
            <b>Selected Customer Names:</b> @ViewBag.MultiName<br />

        </div>

    </div>
</div>
<script type="text/javascript" src="~/Scripts/jquery.min.js"></script>
@*<script type="text/javascript" src="~/Scripts/lib-UI-jquery-js-jquery-ui-1.9.2.custom.min.js"></script>*@
<script src="~/Scripts/jquery-ui1.9.1.js"></script>

@using (Html.BeginForm("FormsConfirmation", "MultipleDocumentDownload", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-lg-12 doc-height">
            <div class="well bs-component">
                <input type=hidden name="customerId">
                @Html.Raw(@ViewBag.WordContent)
            </div>
        </div>
    </div>

    <div id="spinner"><i class="fa fa-4x fa-spinner fa-spin "></i>Please wait..</div>
    <div class="row">
        <div class="col-lg-12">
            <div class="col-md-1">
                <input type="submit" class="btn btn-default" value="Submit" id="btnSubmit" />

            </div>
            <div class="col-md-1"><button type="button" value="Edit" class="btn btn-cancel" id="btnedit" onclick="location.href='@Url.Action("CreateDynamicForm","MultipleDocumentDownload",new { id=Session["CurrentTempAId"]})'">Edit</button></div>
            @*<div class="col-md-1">
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel" onclick="location.href='@Url.Action("SearchTemplate","DocumentManagement", new { id = Convert.ToInt32(Session["OrgId"]) })'">Cancel</button>
                </div>*@
        </div>
    </div>

}
@section Scripts{
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootbox")
    <script type="text/javascript">

        $("#clouse1").draggable();

        $("#row").droppable({
            accept: "#clouse1",
            drop: function (event, ui) {
                var droppable = $(this);
                var draggable = ui.draggable;
                // Move draggable into droppable
                draggable.appendTo(droppable);
                draggable.css({ top: '0px', left: '0px' });
            }
        });

        $("#clouse2").draggable();

        $("#row").droppable({
            accept: "#clouse2",
            drop: function (event, ui) {
                var droppable = $(this);
                var draggable = ui.draggable;
                // Move draggable into droppable
                draggable.appendTo(droppable);
                draggable.css({ top: '0px', left: '0px' });
            }
        });

        $('form').submit(function (e) {
            var currentForm = this;
            e.preventDefault();


            //if ( confirm("Are you sure to delete"))
            //    return true;
            //else{
            //    event.preventDefault();
            //    return false;
            //}


            bootbox.confirm({
                title: 'Document ',
                message: "Are You Sure Want to Submit? After That You Can't Edit The Field Values",
                buttons: {
                    'cancel': {
                        label: 'No',
                        className: 'btn-cancel pull-left'
                    },
                    'confirm': {
                        label: 'Yes',
                        className: 'btn-default pull-right'
                    }
                },
                callback: function (result) {
                    if (result) {
                        showProgress();
                        currentForm.submit();

                        //return true;
                        //document.form.action = "FormsConfirmation";
                        //document.form.submit();

                    }

                }
            });


        });


        var spinnerVisible = false;
        function showProgress() {
            if (!spinnerVisible) {
                $("div#spinner").fadeIn("fast");
                spinnerVisible = true;

            }
        };
        function hideProgress() {
            if (spinnerVisible) {
                var spinner = $("div#spinner");
                spinner.stop();
                spinner.fadeOut("fast");
                spinnerVisible = false;
            }
        };
    </script>

}