VirtualAdvocate/Controllers/UsersRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using VirtualAdvocate.BLL;
using VirtualAdvocate.Common;
using VirtualAdvocate.DAL;
using VirtualAdvocate.Models;
namespace VirtualAdvocate.Controllers
{
    public class UsersRegistrationController : Controller
    {
        private VirtualAdvocateDocumentData objData = new VirtualAdvocateDocumentData();

        // GET: UsersRegistration
        public ActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public ActionResult Registration(int? id)
        {
            VirtualAdvocateData objData = new VirtualAdvocateData();
            UserRegistrationModel obj = objData.getDefaultRegistration(id);
            List<OptionsModel> objOrgType = new List<OptionsModel>();
            objOrgType= objData.getOrganizationTypesOptionsList();
            obj.getAllOrganizationTypes = objOrgType;
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registration(UserRegistrationModel objUserRegistration,FormCollection fc)
        {
             
            int userId = 0;
            int newOrgId = 0;
            LogRegistration objLog = new LogRegistration();
            using (VirtualAdvocateEntities objContext = new VirtualAdvocateEntities())
            {
    
                    try
                    {
                        var success = false;
                        VirtualAdvocateData objData = new VirtualAdvocateData();
                        UserProfile objUP = new UserProfile();
                        if (objUserRegistration.UserAccountType == 1)
                        {
                            objUP.RoleId = 3;
                            objLog.RoleId = 3;
                        }
                        else
                        {
                            objUP.RoleId = 2;
                            objLog.RoleId = 2;
                        }
                        objUP.EmailAddress = objUserRegistration.EmailAddress;
                    if (Session["RoleId"]!=null && Session["RoleId"].ToString() == "1")
                    {
                        objUP.IsEnabled = true;
                        objUP.HasActivated = true;
                    }
                    else
                    {
                        objUP.IsEnabled = false;
                        objUP.HasActivated = false;
                    }
                        objUP.Password = Crypto.HashPassword(objUserRegistration.password);
                        objUP.IsMailSent = true;
                        objUP.CreatedDate = DateTime.Now;
                      //  objUP.TermsConditions = objUserRegistration.TermsConditions;
                        try
                        {
                            userId = objData.SaveUserProfile(objUP);
                            success = true;
                        }
                        catch(Exception ex)
                        {
                            success = false;
                            ErrorLog.LogThisError(ex);
                        }

                    if (userId != 0)
                    {
                        OrganizationDetail org = new OrganizationDetail();
                        org.UserId = userId;
                        org.OrgName = objUserRegistration.OrgName;
                        org.OrgEmail = objUserRegistration.OrgEmail;
                        org.OrgPhoneNumber = objUserRegistration.OrgPhoneNumber;
                        org.OrgStreetName = objUserRegistration.OrgStreetName;
                        org.OrgPlotNo = objUserRegistration.OrgPlotNo;
                        org.OrgRegion = objUserRegistration.OrgRegion;
                        org.OrgBuildingName = objUserRegistration.OrgBuildingName;
                        org.OrgLandMark = objUserRegistration.OrgLandMark;
                        org.OrgBlockNo = objUserRegistration.OrgBlockNo;
                        org.UserAccountsType = objUserRegistration.UserAccountType;
                        org.OrganizationTypeId = objUserRegistration.OrganizationTypeId;

                        if (Session["RoleId"] != null && Session["RoleId"].ToString() == "1")


                            org.IsEnabled = true;
                        else
                            org.IsEnabled = false;
                        org.CreatedDate = DateTime.Now;
                        try
                        {
                            newOrgId = objData.SaveOrganizationDetails(org);
                            UserProfile objUPOrgId = new UserProfile();
                            objUPOrgId = objContext.UserProfiles.Find(userId);
                            objUPOrgId.OrganizationId = newOrgId;
                            objContext.SaveChanges();
                            success = true;
                        }
                        catch (Exception ex)
                        {
                            success = false;
                            ErrorLog.LogThisError(ex);
                        }
                        UserAddressDetail objAddress = new UserAddressDetail();
                        objAddress.UserId = userId;
                        objAddress.FirstName = objUserRegistration.FirstName;
                        objAddress.LastName = objUserRegistration.LastName;
                        objAddress.Designation = objUserRegistration.Designation;
                        objAddress.CreatedDate = DateTime.Now;
                        try
                        {
                            objData.SaveUserPersonalDetails(objAddress);
                            success = true;
                        }
                        catch (Exception ex)
                        {
                            success = false;
                            ErrorLog.LogThisError(ex);
                        }

                     
                      
                            var selectedPayments = new List<PaymentMethodModel>();
                            var postedPaymentTypeIds = new string[0];
                            if (objUserRegistration.PostedPaymentMethods == null) objUserRegistration.PostedPaymentMethods = new PostedPaymentMethods();


                            // if a view model array of posted payment
                            // and is not empty,save selected ids
                            if (objUserRegistration.PostedPaymentMethods.PaymentTypeIds != null)
                            {
                                SelectedPaymentMethod objPM = new SelectedPaymentMethod();

                                postedPaymentTypeIds = objUserRegistration.PostedPaymentMethods.PaymentTypeIds;
                                for (int i = 0; i < postedPaymentTypeIds.Length; i++)
                                {
                                    objPM.PaymentTypeId = Convert.ToInt32(postedPaymentTypeIds[i]);
                                    objPM.UserId = userId;
                                    objData.SaveSelectedPaymentMethod(objPM);
                                }

                            }

                        }


                    var selectedDepartments = new List<DepartmentModel>();
                    var postedDepartmentsIds = new string[0];
                    if (objUserRegistration.PostedDepartment == null) objUserRegistration.PostedDepartment = new PostedDepartment();


                    // if a view model array of posted payment
                    // and is not empty,save selected ids
                    if (objUserRegistration.PostedDepartment.DepartmentIds != null)
                    {
                        SelectedDepartment objDep = new SelectedDepartment();

                        postedDepartmentsIds = objUserRegistration.PostedDepartment.DepartmentIds;
                        for (int i = 0; i < postedDepartmentsIds.Length; i++)
                        {
                            objDep.DepartmentId = Convert.ToInt32(postedDepartmentsIds[i]);
                            objDep.OrgID = newOrgId;
                            objData.SaveSelectedDepartment(objDep);
                        }

                    }

                    //Adding customer Template
                    if (objUserRegistration.extraFields != null)
                    {
                        if (objUserRegistration.extraFields.Count() > 0)
                        {

                            foreach (ClientWiseCustomerTemplate item in objUserRegistration.extraFields)
                            {
                                item.KeyName = item.KeyName == null ? "Name" : item.KeyName;
                                var key = objContext.ClientWiseCustomerTemplates.Where(c => c.ClientID == newOrgId && c.KeyName == item.KeyName).FirstOrDefault();
                                var customerKey = objContext.TemplateKeywords.Where(t => t.TemplateKeyValue == item.KeyName.Replace(" ", "_")).FirstOrDefault();
                                if (key == null)
                                {
                                    ClientWiseCustomerTemplate objExtra = new ClientWiseCustomerTemplate();
                                    objExtra.ClientID = newOrgId;
                                    objExtra.KeyName = item.KeyName;
                                    objExtra.Show = item.Show;

                                    objContext.ClientWiseCustomerTemplates.Add(objExtra);

                                }
                                if (customerKey == null)
                                {
                                    TemplateKeyword keyObj = new TemplateKeyword();

VirtualAdvocate/Views/UsersRegistration/About.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>About</h2>

VirtualAdvocate/Views/UsersRegistration/ChangePassword.cshtml
@model VirtualAdvocate.Models.ChangePassword
@{
    ViewBag.MenuActive = "DashBoard";
    //ViewBag.Title = "ChangePassword";
    Layout = "~/Views/Shared/_Layoutmain.cshtml";
}

<h2>CHANGE PASSWORD</h2>

@using (Html.BeginForm("", "", FormMethod.Post, new { @class = "form-horizontal", id = "ChangePasswordForm" , onsubmit = "showProgress()" }))
{
    @Html.AntiForgeryToken()
    <hr />

    <div class="alert-box success" style="display: none;">
        <span>success: </span><span class="successMessage">message</span>
    </div>
    <div class="alert-box errorMsg" style="display: none;">
        <span>error: </span><span class="errorMessage">message</span>
    </div>

    <div class="form-group">
        <div class="col-lg-4 control-label">
        </div>
        <div class="col-lg-6">
            <span class="text-danger">@ViewBag.message</span>
        </div>
    </div>
    <div class="row">
        @if (Convert.ToInt32(Session["RoleId"]) != 3 && Convert.ToInt32(Session["RoleId"]) != 5 )
        {
        <div  class="col-lg-12">
            <div class="navbar-form navbar-right">
                <label>@Html.RadioButton("Pwd", "MyPassword",true)My Password</label>
                <label>@Html.RadioButton("Pwd", "Others")Others</label>
            </div>
            </div>
        }
        <div class="col-lg-6">
@if (Convert.ToInt32(Session["RoleId"]) != 3 && Convert.ToInt32(Session["RoleId"]) != 5 )
{
            <div class="form-group" id="users" style="display:none">
                @Html.Label("Select Users", new { @class = "col-lg-6 control-label" })
                <div class="col-lg-6">
                    @Html.DropDownListFor(m => m.userId, new SelectList(Model.getAllUsers, "ID", "Name"), "-Select-", new { @class = "form-control" })
                </div>
            </div>
}
            <div class="form-group">
                @Html.LabelFor(m => m.password, new { @class = "col-lg-6 control-label" })

                <div class="col-lg-6">
                    @Html.PasswordFor(m => m.password, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.password, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.newpassword, new { @class = "col-lg-6 control-label" })

                <div class="col-lg-6">
                    @Html.PasswordFor(m => m.newpassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.newpassword, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Confirmpassword, new { @class = "col-lg-6 control-label" })
                <div class="col-lg-6">
                    @Html.PasswordFor(m => m.Confirmpassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Confirmpassword, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
           
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="form-group">
                <div class="col-md-offset-2">
                    <input type="submit" class="btn btn-default" id="ChangePassword" value="Change Password" />&nbsp;&nbsp;    
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel" onclick="history.go(-1);">Cancel</button>
                </div>
                
            </div>
        </div>
    </div>




}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">

        function ShowSuccess(message) {
            $(".successMessage").text(message);
            $(".success").delay(0).fadeIn("slow");
            $(".success").delay(3000).fadeOut("slow");
        }
        function ShowError(message) {
            $(".errorMessage").text(message);
            $(".errorMsg").delay(0).fadeIn("slow");
            $(".errorMsg").delay(3000).fadeOut("slow");
        }
        $(document).ajaxError(function (e, jqxhr, settings, exception) {
            if (jqxhr.readyState == 0 || jqxhr.status == 0) {
                alert("sddssd");
                return; //Skip this error
            }
        });

        $(document).ready(function () {
            var resetButton = $("#ChangePassword");
            var resetPasswordForm = $("#ChangePasswordForm");
            resetButton.click(function (e) {
                e.preventDefault();
                if (resetPasswordForm.valid()) {
                    showProgress();
                    $.ajax({
                        type: "POST",
                        dataType: "json",
                        contentType: "application/json",
                        url: "../ChangePassword",
                        data: JSON.stringify(resetPasswordForm.serializeObject()),
                        beforeSend: function () { resetButton.prop("disabled", true); resetButton.val("Processing...") }
                    })
        .success(function (data) {
            if (data.success) {
                ShowSuccess(data.message);
                setTimeout(function () {
                    window.location.href = '@Url.Content("~/Login/Index")';
                }, 2002);

            }
            else
                ShowError(data.message);
            resetButton.prop("disabled", false);
            resetButton.val("Change Password");

        })
        .error(function (xhr, status, error) {
            ShowError(error);
            resetButton.prop("disabled", false);
            resetButton.val("Change Password");
        });
                    return false;
                }
            });

            jQuery.fn.serializeObject = function () {
                debugger;
                var arrayData, objectData;
                arrayData = this.serializeArray();
                objectData = {};

                $.each(arrayData, function () {
                    var value;

                    if (this.value != null) {
                        value = this.value;
                    } else {
                        value = '';
                    }

                    if (objectData[this.name] != null) {
                        if (!objectData[this.name].push) {
                            objectData[this.name] = [objectData[this.name]];
                        }

                        objectData[this.name].push(value);
                    } else {
                        objectData[this.name] = value;
                    }
                });

                return objectData;
            };

        });

    $('input:radio').change(function () {
        $("#users").toggle();
    });


</script>
}

VirtualAdvocate/Views/UsersRegistration/Contact.cshtml
@{
    ViewBag.Title = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Contact</h2>

VirtualAdvocate/Views/UsersRegistration/DueDiligenceRegister.cshtml
@using MvcCheckBoxList.Model
@model VirtualAdvocate.Models.DueDiligenceUserViewModel

@{
    //ViewBag.Title = "DueDiligence";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>DUE DILIGENCE</h2>

@using (Html.BeginForm("DueDiligenceRegister", "UsersRegistration", FormMethod.Post, new {
    @class = "form-horizontal", role = "form",
    onsubmit = "showProgress()"
}))
{
    @Html.AntiForgeryToken()
    <hr />
   
    <div class="row">
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>Inquiry Type</legend>
                    <div class="form-group">
                        <div class="col-lg-6 form-inline">
                            <div class="radio col-lg-4">
                                <label>
                                    @Html.RadioButtonFor(m => m.EnquiryType, "1") Business
                                </label>
                            </div>
                            <div class="radio col-lg-4">
                                <label>
                                    @Html.RadioButtonFor(m => m.EnquiryType, "2") Company
                                </label>
                            </div>
                            <div class="radio col-lg-4">
                                <label>
                                    @Html.RadioButtonFor(m => m.EnquiryType, "3") Land
                                </label>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>User &amp; Contact Details</legend>

                    <div class="row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <div class="col-lg-10 col-md-offset-1"><h4>Personal Information</h4></div>
                            </div>                          
                            <div class="form-group">
                                @Html.LabelFor(m => m.FirstName, new { @class = "col-lg-4 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder="First Name" })
                                    @Html.ValidationMessageFor(m => m.FirstName, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.LastName, new { @class = "col-lg-4 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                    @Html.ValidationMessageFor(m => m.LastName, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.EmailAddress, new { @class = "col-lg-4 control-label" })                               
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", @placeholder = "Email Address" })
                                    @Html.ValidationMessageFor(m => m.EmailAddress, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.PhoneNumber, new { @class = "col-lg-4 control-label" })
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", @placeholder = "Phone Number" })
                                    @Html.ValidationMessageFor(m => m.PhoneNumber, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.password, new { @class = "col-lg-4 control-label" })                              
                                <div class="col-lg-6">
                                    @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password" })
                                    @Html.ValidationMessageFor(m => m.password, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Confirmpassword, new { @class = "col-lg-4 control-label" })                               
                                <div class="col-lg-6">
                                    @Html.PasswordFor(m => m.Confirmpassword, new { @class = "form-control", @placeholder = "Confirm Password" })
                                    @Html.ValidationMessageFor(m => m.Confirmpassword, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <div class="col-lg-10 col-md-offset-1"><h4>Contact Information</h4></div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.StreetName, new { @class = "col-lg-4 control-label" })                               
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.StreetName, new { @class = "form-control", @placeholder = "Street Name" })
                                    @Html.ValidationMessageFor(m => m.StreetName, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.BuildingName, new { @class = "col-lg-4 control-label" })                              
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.BuildingName, new { @class = "form-control", @placeholder = "Building Name" })
                                    @Html.ValidationMessageFor(m => m.BuildingName, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.PlotNo, new { @class = "col-lg-4 control-label" })
                               
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.PlotNo, new { @class = "form-control", @placeholder = "Plot Number" })
                                    @Html.ValidationMessageFor(m => m.PlotNo, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.BlockNo, new { @class = "col-lg-4 control-label" })                              
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.BlockNo, new { @class = "form-control", @placeholder = "Block Number" })
                                    @Html.ValidationMessageFor(m => m.BlockNo, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.Region, new { @class = "col-lg-4 control-label" })                               
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.Region, new { @class = "form-control", @placeholder = "Region" })
                                    @Html.ValidationMessageFor(m => m.Region, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(m => m.LandMark, new { @class = "col-lg-4 control-label" })                               
                                <div class="col-lg-6">
                                    @Html.TextBoxFor(m => m.LandMark, new { @class = "form-control", @placeholder = "Land Mark" })
                                    @Html.ValidationMessageFor(m => m.LandMark, string.Empty, new { @class = "text-danger" })
                                </div>
                            </div>

                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>Preferred Payment Method</legend>
                    <div class="form-group">
                        <div class="col-lg-6 form-inline">
                            @Html.CheckBoxListFor(model => model.PostedPaymentMethods.PaymentTypeIds, model => model.AvailablePaymentMethods, m => m.Id, m => m.Name, model => model.SelectedPaymentMethods,MvcCheckBoxList.Model.Position.Horizontal)
                            @Html.ValidationMessageFor(model => model.PostedPaymentMethods.PaymentTypeIds, string.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="col-lg-12">
            <div class="well bs-component">
                <fieldset>
                    <legend>Terms & Conditions</legend>
                    <div class="form-group">
                        @*<label class="col-lg-4 control-label">Terms & Conditions</label>*@
                        <div class="col-lg-8">
                            @Html.CheckBoxFor(model => model.TermsConditions)&nbsp;I have read and agree to the Terms & Conditions
                            @Html.ValidationMessageFor(model => model.TermsConditions, string.Empty, new { @class = "text-danger" })
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="col-md-1">
                    <input type="submit" class="btn btn-default" id="btnSubmit" value="Submit" />
                </div>
                <div class="">
                    <button type="button" value="Cancel" class="btn btn-cancel" id="btncancel" onclick="location.href='@Url.Action("Index", "Login")'">Cancel</button>
                </div>
                               
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript" >
    $(function () {

        $('input[name="PostedPaymentMethods.PaymentTypeIds"]').rules('add', {
    required: true,
    messages: {
        required: "Select atleast one payment method"
    }
});

});
    $(function () {

        $('input[name="TermsConditions"]').rules('add', {
            required: true,
            messages: {
                required: "Please Accept The Terms & Conditions"
            }
        });

    });
</script>
}

VirtualAdvocate/Views/UsersRegistration/ForgotPassword.cshtml
@model VirtualAdvocate.Models.ForgotPasswordViewModel
@{
    //ViewBag.Title = "Forgot your password?";
}

<h2>FORGOT PASSWORD</h2>

@using (Html.BeginForm("ForgotPassword", "UsersRegistration", FormMethod.Post, new { @class = "form-horizontal", role = "form" , onsubmit = "showProgress()" }))
{
    @Html.AntiForgeryToken()
    <h4>Enter your email.</h4>
    <hr />
    <div class="form-group">
        <div class="col-lg-4 control-label">
         </div>
            <div class="col-lg-6">
                <span class="text-danger">@ViewBag.StatusMessage</span>
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.EmailAddress, new { @class = "col-lg-4 control-label" })
            <div class="col-lg-6">
                @Html.TextBoxFor(m => m.EmailAddress, new { @class = "form-control", maxlength = 50, @placeholder="Email Address" })
                @Html.ValidationMessageFor(m => m.EmailAddress, string.Empty, new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" class="btn btn-default" value="Email Link" /> 
            </div>
            <div class="col-lg-10">
               <a href="@Url.Action("Index", "Login")">I remembered my password !</a>
            </div>
        </div>
       
}

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

VirtualAdvocate/Views/UsersRegistration/LogOff.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>LogOff</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

VirtualAdvocate/Views/UsersRegistration/Policy.cshtml
@{
    ViewBag.Title = "Policy";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Policy</h2>

VirtualAdvocate/Views/UsersRegistration/ResetPasswordConfirmation.cshtml
@{
    //ViewBag.Title = "Reset password confirmation";
}

<hgroup class="title">
    <h2>RESET PASSWORD CONFIRMATION</h2>
</hgroup>
<div>
    <p>
        Your password has been reset. Please @Html.ActionLink("click here to log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
    </p>
</div>

VirtualAdvocate/Views/UsersRegistration/Terms.cshtml
@{
    ViewBag.Title = "Terms";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Terms</h2>